In [4]:
import numpy as np
import pandas as pd

pd.read_csv('學生第一學期分數.csv',index_col=0)

    國文  英文  數學  地理  歷史   總分    平均
1   77  77  74  62  83  373  74.6
2   70  90  66  60  89  375  75.0
3   89  63  62  99  95  408  81.6
4   60  87  75  85  93  400  80.0
5   64  66  63  75  65  333  66.6
6   63  73  73  93  99  401  80.2
7   69  80  83  79  63  374  74.8
8   60  67  71  64  80  342  68.4
9   83  64  63  82  66  358  71.6
10  92  91  75  88  76  422  84.4
11  65  75  90  81  65  376  75.2
12  72  72  61  97  85  387  77.4
13  62  60  71  94  74  361  72.2
14  98  84  81  63  82  408  81.6
15  64  93  85  63  70  375  75.0
16  88  77  90  83  77  415  83.0
17  76  68  89  77  80  390  78.0
18  83  94  90  96  95  458  91.6
19  71  73  76  70  89  379  75.8
20  86  62  95  62  97  402  80.4
21  69  93  74  90  92  418  83.6
22  60  61  73  64  61  319  63.8
23  96  85  74  61  78  394  78.8
24  70  74  78  98  66  386  77.2
25  81  88  79  88  87  423  84.6
26  80  81  64  89  96  410  82.0
27  74  93  95  77  79  418  83.6
28  84  73  71  80  66  374  74.8
29  80  85  78  91  89  423  84.6
30  85  68  68  65  61  347  69.4
31  68  84  85  89  74  400  80.0
32  61  87  84  73  89  394  78.8
33  70  90  84  86  91  421  84.2
34  66  84  79  82  92  403  80.6
35  65  61  71  62  82  341  68.2
36  63  96  92  89  82  422  84.4
37  81  98  67  79  81  406  81.2
38  60  75  97  97  80  409  81.8
39  64  63  94  86  79  386  77.2
40  93  78  79  73  86  409  81.8
41  91  63  88  87  99  428  85.6
42  76  66  97  82  84  405  81.0
43  71  95  87  69  84  406  81.2
44  97  85  77  85  79  423  84.6
45  90  67  81  85  70  393  78.6
46  84  76  77  97  73  407  81.4
47  90  68  72  68  63  361  72.2
48  96  68  85  69  85  403  80.6
49  83  70  68  75  71  367  73.4
50  76  92  74  78  89  409  81.8

In [5]:
df = pd.read_csv('學生第一學期分數.csv')
df.columns = ["學號","國文","英文","數學","地理","歷史","總分","平均"]
df

    學號  國文  英文  數學  地理  歷史   總分    平均
0    1  77  77  74  62  83  373  74.6
1    2  70  90  66  60  89  375  75.0
2    3  89  63  62  99  95  408  81.6
3    4  60  87  75  85  93  400  80.0
4    5  64  66  63  75  65  333  66.6
5    6  63  73  73  93  99  401  80.2
6    7  69  80  83  79  63  374  74.8
7    8  60  67  71  64  80  342  68.4
8    9  83  64  63  82  66  358  71.6
9   10  92  91  75  88  76  422  84.4
10  11  65  75  90  81  65  376  75.2
11  12  72  72  61  97  85  387  77.4
12  13  62  60  71  94  74  361  72.2
13  14  98  84  81  63  82  408  81.6
14  15  64  93  85  63  70  375  75.0
15  16  88  77  90  83  77  415  83.0
16  17  76  68  89  77  80  390  78.0
17  18  83  94  90  96  95  458  91.6
18  19  71  73  76  70  89  379  75.8
19  20  86  62  95  62  97  402  80.4
20  21  69  93  74  90  92  418  83.6
21  22  60  61  73  64  61  319  63.8
22  23  96  85  74  61  78  394  78.8
23  24  70  74  78  98  66  386  77.2
24  25  81  88  79  88  87  423  84.6
25  26  80  81  64  89  96  410  82.0
26  27  74  93  95  77  79  418  83.6
27  28  84  73  71  80  66  374  74.8
28  29  80  85  78  91  89  423  84.6
29  30  85  68  68  65  61  347  69.4
30  31  68  84  85  89  74  400  80.0
31  32  61  87  84  73  89  394  78.8
32  33  70  90  84  86  91  421  84.2
33  34  66  84  79  82  92  403  80.6
34  35  65  61  71  62  82  341  68.2
35  36  63  96  92  89  82  422  84.4
36  37  81  98  67  79  81  406  81.2
37  38  60  75  97  97  80  409  81.8
38  39  64  63  94  86  79  386  77.2
39  40  93  78  79  73  86  409  81.8
40  41  91  63  88  87  99  428  85.6
41  42  76  66  97  82  84  405  81.0
42  43  71  95  87  69  84  406  81.2
43  44  97  85  77  85  79  423  84.6
44  45  90  67  81  85  70  393  78.6
45  46  84  76  77  97  73  407  81.4
46  47  90  68  72  68  63  361  72.2
47  48  96  68  85  69  85  403  80.6
48  49  83  70  68  75  71  367  73.4
49  50  76  92  74  78  89  409  81.8

In [6]:
df = pd.read_csv('學生第一學期分數.csv')
df1 = df.rename(columns={'Unnamed: 0':"學號"})
df1

    學號  國文  英文  數學  地理  歷史   總分    平均
0    1  77  77  74  62  83  373  74.6
1    2  70  90  66  60  89  375  75.0
2    3  89  63  62  99  95  408  81.6
3    4  60  87  75  85  93  400  80.0
4    5  64  66  63  75  65  333  66.6
5    6  63  73  73  93  99  401  80.2
6    7  69  80  83  79  63  374  74.8
7    8  60  67  71  64  80  342  68.4
8    9  83  64  63  82  66  358  71.6
9   10  92  91  75  88  76  422  84.4
10  11  65  75  90  81  65  376  75.2
11  12  72  72  61  97  85  387  77.4
12  13  62  60  71  94  74  361  72.2
13  14  98  84  81  63  82  408  81.6
14  15  64  93  85  63  70  375  75.0
15  16  88  77  90  83  77  415  83.0
16  17  76  68  89  77  80  390  78.0
17  18  83  94  90  96  95  458  91.6
18  19  71  73  76  70  89  379  75.8
19  20  86  62  95  62  97  402  80.4
20  21  69  93  74  90  92  418  83.6
21  22  60  61  73  64  61  319  63.8
22  23  96  85  74  61  78  394  78.8
23  24  70  74  78  98  66  386  77.2
24  25  81  88  79  88  87  423  84.6
25  26  80  81  64  89  96  410  82.0
26  27  74  93  95  77  79  418  83.6
27  28  84  73  71  80  66  374  74.8
28  29  80  85  78  91  89  423  84.6
29  30  85  68  68  65  61  347  69.4
30  31  68  84  85  89  74  400  80.0
31  32  61  87  84  73  89  394  78.8
32  33  70  90  84  86  91  421  84.2
33  34  66  84  79  82  92  403  80.6
34  35  65  61  71  62  82  341  68.2
35  36  63  96  92  89  82  422  84.4
36  37  81  98  67  79  81  406  81.2
37  38  60  75  97  97  80  409  81.8
38  39  64  63  94  86  79  386  77.2
39  40  93  78  79  73  86  409  81.8
40  41  91  63  88  87  99  428  85.6
41  42  76  66  97  82  84  405  81.0
42  43  71  95  87  69  84  406  81.2
43  44  97  85  77  85  79  423  84.6
44  45  90  67  81  85  70  393  78.6
45  46  84  76  77  97  73  407  81.4
46  47  90  68  72  68  63  361  72.2
47  48  96  68  85  69  85  403  80.6
48  49  83  70  68  75  71  367  73.4
49  50  76  92  74  78  89  409  81.8

In [9]:
display(df1['總分'])
df1['總分'].rank(ascending=False,method="min")

0     373
1     375
2     408
3     400
4     333
5     401
6     374
7     342
8     358
9     422
10    376
11    387
12    361
13    408
14    375
15    415
16    390
17    458
18    379
19    402
20    418
21    319
22    394
23    386
24    423
25    410
26    418
27    374
28    423
29    347
30    400
31    394
32    421
33    403
34    341
35    422
36    406
37    409
38    386
39    409
40    428
41    405
42    406
43    423
44    393
45    407
46    361
47    403
48    367
49    409
Name: 總分, dtype: int64

0     41.0
1     37.5
2     16.5
3     26.5
4     49.0
5     25.0
6     39.5
7     47.0
8     45.0
9      6.5
10    36.0
11    32.0
12    43.5
13    16.5
14    37.5
15    11.0
16    31.0
17     1.0
18    35.0
19    24.0
20     9.5
21    50.0
22    28.5
23    33.5
24     4.0
25    12.0
26     9.5
27    39.5
28     4.0
29    46.0
30    26.5
31    28.5
32     8.0
33    22.5
34    48.0
35     6.5
36    19.5
37    14.0
38    33.5
39    14.0
40     2.0
41    21.0
42    19.5
43     4.0
44    30.0
45    18.0
46    43.5
47    22.5
48    42.0
49    14.0
Name: 總分, dtype: float64

In [10]:
df1['排名'] = df1['總分'].rank(ascending=False,method="min")
df1

    學號  國文  英文  數學  地理  歷史   總分    平均    排名
0    1  77  77  74  62  83  373  74.6  41.0
1    2  70  90  66  60  89  375  75.0  37.0
2    3  89  63  62  99  95  408  81.6  16.0
3    4  60  87  75  85  93  400  80.0  26.0
4    5  64  66  63  75  65  333  66.6  49.0
5    6  63  73  73  93  99  401  80.2  25.0
6    7  69  80  83  79  63  374  74.8  39.0
7    8  60  67  71  64  80  342  68.4  47.0
8    9  83  64  63  82  66  358  71.6  45.0
9   10  92  91  75  88  76  422  84.4   6.0
10  11  65  75  90  81  65  376  75.2  36.0
11  12  72  72  61  97  85  387  77.4  32.0
12  13  62  60  71  94  74  361  72.2  43.0
13  14  98  84  81  63  82  408  81.6  16.0
14  15  64  93  85  63  70  375  75.0  37.0
15  16  88  77  90  83  77  415  83.0  11.0
16  17  76  68  89  77  80  390  78.0  31.0
17  18  83  94  90  96  95  458  91.6   1.0
18  19  71  73  76  70  89  379  75.8  35.0
19  20  86  62  95  62  97  402  80.4  24.0
20  21  69  93  74  90  92  418  83.6   9.0
21  22  60  61  73  64  61  319  63.8  50.0
22  23  96  85  74  61  78  394  78.8  28.0
23  24  70  74  78  98  66  386  77.2  33.0
24  25  81  88  79  88  87  423  84.6   3.0
25  26  80  81  64  89  96  410  82.0  12.0
26  27  74  93  95  77  79  418  83.6   9.0
27  28  84  73  71  80  66  374  74.8  39.0
28  29  80  85  78  91  89  423  84.6   3.0
29  30  85  68  68  65  61  347  69.4  46.0
30  31  68  84  85  89  74  400  80.0  26.0
31  32  61  87  84  73  89  394  78.8  28.0
32  33  70  90  84  86  91  421  84.2   8.0
33  34  66  84  79  82  92  403  80.6  22.0
34  35  65  61  71  62  82  341  68.2  48.0
35  36  63  96  92  89  82  422  84.4   6.0
36  37  81  98  67  79  81  406  81.2  19.0
37  38  60  75  97  97  80  409  81.8  13.0
38  39  64  63  94  86  79  386  77.2  33.0
39  40  93  78  79  73  86  409  81.8  13.0
40  41  91  63  88  87  99  428  85.6   2.0
41  42  76  66  97  82  84  405  81.0  21.0
42  43  71  95  87  69  84  406  81.2  19.0
43  44  97  85  77  85  79  423  84.6   3.0
44  45  90  67  81  85  70  393  78.6  30.0
45  46  84  76  77  97  73  407  81.4  18.0
46  47  90  68  72  68  63  361  72.2  43.0
47  48  96  68  85  69  85  403  80.6  22.0
48  49  83  70  68  75  71  367  73.4  42.0
49  50  76  92  74  78  89  409  81.8  13.0

In [12]:
df2 = df1.sort_values(by='排名')

In [13]:
display(df2.iloc[:5])
display(df2.iloc[-5:])

    學號  國文  英文  數學  地理  歷史   總分    平均   排名
17  18  83  94  90  96  95  458  91.6  1.0
40  41  91  63  88  87  99  428  85.6  2.0
24  25  81  88  79  88  87  423  84.6  3.0
43  44  97  85  77  85  79  423  84.6  3.0
28  29  80  85  78  91  89  423  84.6  3.0

    學號  國文  英文  數學  地理  歷史   總分    平均    排名
29  30  85  68  68  65  61  347  69.4  46.0
7    8  60  67  71  64  80  342  68.4  47.0
34  35  65  61  71  62  82  341  68.2  48.0
4    5  64  66  63  75  65  333  66.6  49.0
21  22  60  61  73  64  61  319  63.8  50.0

In [15]:
df2.to_excel("學生第一學期分數.xlsx")